FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml poetry.lock /app/
RUN pip install --no-cache-dir poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-root --no-interaction --no-ansi --only main


COPY pipeline /app/pipeline
COPY sql /app/sql

CMD ["python", "-m", "pipeline.run_daily"]